/**
 * FlowrouteNumbersAndMessagingLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

'use strict';

const APIError = require('../lib/Models/APIError');
const MessageAttributes = require('../lib/Models/MessageAttributes');
const MDR2 = require('../lib/Models/MDR2');
const NumberAttributes = require('../lib/Models/NumberAttributes');
const DeliveryReceipt = require('../lib/Models/DeliveryReceipt');
const PhoneNumber = require('../lib/Models/PhoneNumber');
const NumberDataobject = require('../lib/Models/NumberDataobject');
const RouteAttributes = require('../lib/Models/RouteAttributes');
const Links = require('../lib/Models/Links');
const NewRoute = require('../lib/Models/NewRoute');
const RouteDataobject = require('../lib/Models/RouteDataobject');
const AccountRoutes = require('../lib/Models/AccountRoutes');
const Message = require('../lib/Models/Message');
const CNAM = require('../lib/Models/CNAM');
const MDR2Attributes = require('../lib/Models/MDR2Attributes');
const E911Address = require('../lib/Models/E911Address');
const E911Dataobject = require('../lib/Models/E911Dataobject');
const E911Attributes = require('../lib/Models/E911Attributes');

const classMap = {
    APIError,
    MessageAttributes,
    MDR2,
    NumberAttributes,
    DeliveryReceipt,
    PhoneNumber,
    NumberDataobject,
    RouteAttributes,
    Links,
    NewRoute,
    RouteDataobject,
    AccountRoutes,
    Message,
    CNAM,
    MDR2Attributes,
    E911Address,
    E911Dataobject,
    E911Attributes,
};

/**
 * Factory class to create instances of models and exception classes
 */
class ModelFactory {
    /**
     * Creates instance of a model class
     * @param  modelName  {string}  Name of class to instantiate
     * @returns  {object} Instance of the model class
     */
    static getInstance(modelName) {
        return new classMap[modelName]();
    }
}

module.exports = ModelFactory;
