/**
 * FlowrouteNumbersAndMessagingLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

'use strict';

const BaseModel = require('./BaseModel');

/**
 * Creates an instance of DeliveryReceipt
 */
class DeliveryReceipt extends BaseModel {
    /**
     * @constructor
     * @param   {Object}  obj    The object passed to constructor
     */
    constructor(obj) {
        super(obj);
        if (obj === undefined || obj === null) return;
        this.level = this.constructor.getValue(obj.level);
        this.status = this.constructor.getValue(obj.status);
        this.statusCode = this.constructor.getValue(obj.statusCode || obj.status_code);
        this.statusCodeDescription =
          this.constructor.getValue(obj.statusCodeDescription
     || obj.status_code_description);
        this.timestamp = this.constructor.getValue(obj.timestamp);
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'level', realName: 'level' },
            { name: 'status', realName: 'status' },
            { name: 'statusCode', realName: 'status_code' },
            { name: 'statusCodeDescription', realName: 'status_code_description' },
            {
                name: 'timestamp',
                realName: 'timestamp',
                isDateTime: true,
                dateTimeValue: 'rfc3339',
            },
        ]);
    }

    /**
     * Function containing information about discriminator values
     * mapped with their corresponding model class names
     *
     * @return   {object}  Object containing Key-Value pairs mapping discriminator
     *                     values with their corresponding model classes
     */
    static discriminatorMap() {
        return {};
    }
}

module.exports = DeliveryReceipt;
