/**
 * FlowrouteNumbersAndMessagingLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

'use strict';

const BaseModel = require('./BaseModel');

/**
 * Creates an instance of E911Attributes
 */
class E911Attributes extends BaseModel {
    /**
     * @constructor
     * @param   {Object}  obj    The object passed to constructor
     */
    constructor(obj) {
        super(obj);
        if (obj === undefined || obj === null) return;
        this.addressType = this.constructor.getValue(obj.addressType || obj.address_type);
        this.addressTypeNumber =
          this.constructor.getValue(obj.addressTypeNumber
     || obj.address_type_number);
        this.city = this.constructor.getValue(obj.city);
        this.country = this.constructor.getValue(obj.country);
        this.firstName = this.constructor.getValue(obj.firstName || obj.first_name);
        this.label = this.constructor.getValue(obj.label);
        this.lastName = this.constructor.getValue(obj.lastName || obj.last_name);
        this.state = this.constructor.getValue(obj.state);
        this.streetName = this.constructor.getValue(obj.streetName || obj.street_name);
        this.streetNumber = this.constructor.getValue(obj.streetNumber || obj.street_number);
        this.zip = this.constructor.getValue(obj.zip);
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'addressType', realName: 'address_type' },
            { name: 'addressTypeNumber', realName: 'address_type_number' },
            { name: 'city', realName: 'city' },
            { name: 'country', realName: 'country' },
            { name: 'firstName', realName: 'first_name' },
            { name: 'label', realName: 'label' },
            { name: 'lastName', realName: 'last_name' },
            { name: 'state', realName: 'state' },
            { name: 'streetName', realName: 'street_name' },
            { name: 'streetNumber', realName: 'street_number' },
            { name: 'zip', realName: 'zip' },
        ]);
    }

    /**
     * Function containing information about discriminator values
     * mapped with their corresponding model class names
     *
     * @return   {object}  Object containing Key-Value pairs mapping discriminator
     *                     values with their corresponding model classes
     */
    static discriminatorMap() {
        return {};
    }
}

module.exports = E911Attributes;
