/**
 * FlowrouteNumbersAndMessagingLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

'use strict';

const BaseModel = require('./BaseModel');

/**
 * Creates an instance of MDR2Attributes
 */
class MDR2Attributes extends BaseModel {
    /**
     * @constructor
     * @param   {Object}  obj    The object passed to constructor
     */
    constructor(obj) {
        super(obj);
        if (obj === undefined || obj === null) return;
        this.amountDisplay = this.constructor.getValue(obj.amountDisplay || obj.amount_display);
        this.amountNanodollars =
          this.constructor.getValue(obj.amountNanodollars
     || obj.amount_nanodollars);
        this.body = this.constructor.getValue(obj.body);
        this.deliveryReceipts =
          this.constructor.getValue(obj.deliveryReceipts
     || obj.delivery_receipts);
        this.direction = this.constructor.getValue(obj.direction);
        this.from = this.constructor.getValue(obj.from);
        this.isMms = this.constructor.getValue(obj.isMms || obj.is_mms);
        this.messageEncoding =
          this.constructor.getValue(obj.messageEncoding
     || obj.message_encoding);
        this.messageType = this.constructor.getValue(obj.messageType || obj.message_type);
        this.status = this.constructor.getValue(obj.status);
        this.timestamp = this.constructor.getValue(obj.timestamp);
        this.to = this.constructor.getValue(obj.to);
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'amountDisplay', realName: 'amount_display' },
            { name: 'amountNanodollars', realName: 'amount_nanodollars' },
            { name: 'body', realName: 'body' },
            {
                name: 'deliveryReceipts',
                realName: 'delivery_receipts',
                array: true,
                type: 'DeliveryReceipt',
            },
            { name: 'direction', realName: 'direction' },
            { name: 'from', realName: 'from' },
            { name: 'isMms', realName: 'is_mms' },
            { name: 'messageEncoding', realName: 'message_encoding' },
            { name: 'messageType', realName: 'message_type' },
            { name: 'status', realName: 'status' },
            {
                name: 'timestamp',
                realName: 'timestamp',
                isDateTime: true,
                dateTimeValue: 'rfc3339',
            },
            { name: 'to', realName: 'to' },
        ]);
    }

    /**
     * Function containing information about discriminator values
     * mapped with their corresponding model class names
     *
     * @return   {object}  Object containing Key-Value pairs mapping discriminator
     *                     values with their corresponding model classes
     */
    static discriminatorMap() {
        return {};
    }
}

module.exports = MDR2Attributes;
