/**
 * FlowrouteNumbersAndMessagingLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

'use strict';


const Configuration = {
    // The base Uri for API calls
    BASEURI: 'https://api.flowroute.com',

    // Your Flowroute Access Key
    username: 'UNKNOWN',

    // Your Flowroute Secret Key
    password: 'UNKNOWN',

};

module.exports = Configuration;
