/**
 * FlowrouteNumbersAndMessagingLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

'use strict';

const Error1 = require('../lib/Models/Error1');
const Message = require('../lib/Models/Message');
const MDR2 = require('../lib/Models/MDR2');
const Data = require('../lib/Models/Data');
const Attributes = require('../lib/Models/Attributes');
const DeliveryReceipt = require('../lib/Models/DeliveryReceipt');
const Number26 = require('../lib/Models/Number26');
const Data27 = require('../lib/Models/Data27');
const Attributes28 = require('../lib/Models/Attributes28');
const Links = require('../lib/Models/Links');
const NewRoute = require('../lib/Models/NewRoute');
const Data61 = require('../lib/Models/Data61');
const Attributes62 = require('../lib/Models/Attributes62');
const AccountRoutes = require('../lib/Models/AccountRoutes');
const Error84 = require('../lib/Models/Error84');
const ErrorException = require('../lib/Exceptions/ErrorException');

const classMap = {
    Error1,
    Message,
    MDR2,
    Data,
    Attributes,
    DeliveryReceipt,
    Number26,
    Data27,
    Attributes28,
    Links,
    NewRoute,
    Data61,
    Attributes62,
    AccountRoutes,
    Error84,
    ErrorException,
};

/**
 * Factory class to create instances of models and exception classes
 */
class ModelFactory {
    /**
     * Creates instance of a model class
     * @param  modelName  {string}  Name of class to instantiate
     * @returns  {object} Instance of the model class
     */
    static getInstance(modelName) {
        return new classMap[modelName]();
    }
}

module.exports = ModelFactory;
