/**
 * FlowrouteNumbersAndMessagingLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

'use strict';

const NumberTypeEnum = {

    /**
     * TODO: Write general description for this element
     */
    STANDARD: 'standard',

    /**
     * TODO: Write general description for this element
     */
    TOLLFREE: 'tollfree',

    /**
     * TODO: Write general description for this element
     */
    INUM: 'inum',

};

module.exports = NumberTypeEnum;
