/**
 * FlowrouteNumbersAndMessagingLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

'use strict';

const RouteTypeEnum = {

    /**
     * TODO: Write general description for this element
     */
    SIPREG: 'sip-reg',

    /**
     * TODO: Write general description for this element
     */
    HOST: 'host',

    /**
     * TODO: Write general description for this element
     */
    URI: 'uri',

    /**
     * TODO: Write general description for this element
     */
    NUMBER: 'number',

};

module.exports = RouteTypeEnum;
