/**
 * FlowrouteNumbersAndMessagingLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

'use strict';

const MessageTypeEnum = {

    /**
     * TODO: Write general description for this element
     */
    LONGCODE: 'longcode',

    /**
     * TODO: Write general description for this element
     */
    TOLLFREE: 'toll-free',

};

module.exports = MessageTypeEnum;
